export const INIT_NEW_COURSE = 'INIT_NEW_COURSE';
export const CHANGE_NEW_COURSE_TITLE = 'CHANGE_NEW_COURSE_TITLE';
export const CHANGE_NEW_COURSE_LENGTH = 'CHANGE_NEW_COURSE_LENGTH';
export const CHANGE_NEW_COURSE_CATEGORY = 'CHANGE_NEW_COURSE_CATEGORY';
export const SAVE_COURSE_SUCCESS = 'SAVE_COURSE_SUCCESS';
export const LOAD_COARSES_SUCCESS = 'LOAD_COARSES_SUCCESS';
